_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "/gdrive/My Drive/data/r101_300pro_3x_model.pth"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 15
TEST:
  EVAL_PERIOD: 1000
SOLVER:
  MAX_ITER: 50000
  CHECKPOINT_PERIOD: 1000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.002
  IMS_PER_BATCH: 8
  WARMUP_ITERS: 500
  RESET_ITER: True
  CLIP_GRADIENTS:
    CLIP_TYPE: "value"
DATALOADER:
  ASPECT_RATIO_GROUPING: False
  NUM_WORKERS: 4
  SAMPLER_TRAIN: "ClassAwareSampler"
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  MAX_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 800
  TRAIN_SIZE: 800
  TEST_SIZE: 800
  SCALE_RANGE: [0.9, 1]
  TEST_INPUT_TYPE: 'square'
OUTPUT_DIR: "/content/sparse/"
VERSION: 2