_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [False, False, True, True] # on Res4, Res5
    DEFORM_MODULATED: True
  SparseRCNN:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 15
  PIXEL_STD: [57.375, 57.120, 58.395]
  ROI_HEADS:
    NUM_CLASSES: 15
    SCORE_THRESH_TEST: 0.001
TEST:
  EVAL_PERIOD: 200
SOLVER:
  MAX_ITER: 50000
  CHECKPOINT_PERIOD: 200
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.000025
  IMS_PER_BATCH: 8
  WARMUP_ITERS: 500
  WARMUP_FACTOR: 0.01
  RESET_ITER: True
  CLIP_GRADIENTS:
    CLIP_TYPE: "value"
  AMP:
    ENABLED: True
DATALOADER:
  ASPECT_RATIO_GROUPING: False
  NUM_WORKERS: 4
  SAMPLER_TRAIN: "ClassAwareSampler"
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  MAX_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 800
  TRAIN_SIZE: 800
  TEST_SIZE: 800
  SCALE_RANGE: [0.9, 1]
  TEST_INPUT_TYPE: 'square'
SEED: -1
OUTPUT_DIR: "/content/sparse/"
VERSION: 2